### ISSUE TITLE
[Bug] Z-Image-Turbo: ,`AttributeError: 'NoneType' object has no attribute 'dtype'` on `comfy launch -- --fast`

### ISSUE THREAD

**Issue by phu54321** [nunchaku-tech/ComfyUI-nunchaku#810]
### Checklist

- [x] 1. I have searched for related issues and FAQs (https://nunchaku.tech/docs/nunchaku/faq/faq.html) but was unable to find a solution.
- [x] 2. The issue persists in the latest version.
- [x] 3. Please note that without environment information and a minimal reproducible example, it will be difficult for us to reproduce and address the issue, which may delay our response.
- [x] 4. If your report is a question rather than a bug, please submit it as a discussion at https://github.com/nunchaku-tech/ComfyUI-nunchaku/discussions/new/choose. Otherwise, this issue will be closed.
- [x] 5. I will do my best to describe the issue in English.

### Describe the Bug

ComfyUi has `--fast` option that allows fp16 accumulation instead of default fp32 accumulation, which is known to speed up the general workflow by like, 20%.

ComfyUI-nunchaku crashes with that comfyui launch flag. Backend should work on this environment, either fast or slow.

### Environment

- Windows 11 Pro (25H2) x86_64 ,Windows 11 Pro (25H2) x86_64
- Python version: 3.13.11 | packaged by Anaconda, Inc. | (main, Dec 10 2025, 21:21:58) [MSC v.1929 64 bit (AMD64)]
- ComfyUI version: 0.15.1
- pytorch version: 2.10.0+cu130
- Device: cuda:0 NVIDIA GeForce RTX 5050 Laptop GPU : native
- Nunchaku version: 1.2.1
- ComfyUI-nunchaku version: 1.2.1

using [ComfyUI CLI](https://github.com/Comfy-Org/comfy-cli) for launch with option

`comfy launch -- --fast`

### Reproduction Steps

Launch ComfyUI with fp16 accumulation using either of the command

- `comfy launch -- --fast`
- `python main.py --fast` (when directly launching comfyui this way)

`--fast` part is mandatory for reproduction of the bug.

Try running the nunchaku-comfyui z-image default workflow with `svdq-fp4_r128-z-image-turbo.safetensors`

<img width="2077" height="875" alt="Image" src="https://github.com/user-attachments/assets/a3248c75-5941-4b92-a99f-defad2493ad1" />

---

You will get

```
unet_dtype: torch.bfloat16, manual_cast_dtype: None, svdq_linear_dtype: torch.bfloat16
model weight dtype torch.bfloat16, manual cast: None
model_type FLOW
!!! Exception during processing !!! 'NoneType' object has no attribute 'dtype'
Traceback (most recent call last):
  File "C:\Users\whyask37\Documents\comfy\ComfyUI\execution.py", line 524, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\whyask37\Documents\comfy\ComfyUI\execution.py", line 333, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\whyask37\Documents\comfy\ComfyUI\execution.py", line 307, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\Users\whyask37\Documents\comfy\ComfyUI\execution.py", line 295, in process_inputs
    result = f(**inputs)
  File "C:\Users\whyask37\Documents\comfy\ComfyUI\custom_nodes\ComfyUI-nunchaku\nodes\models\zimage.py", line 215, in load_model
    model = _load(sd, metadata=metadata)
  File "C:\Users\whyask37\Documents\comfy\ComfyUI\custom_nodes\ComfyUI-nunchaku\nodes\models\zimage.py", line 148, in _load
    model = model_config.get_model(patched_sd, "", torch_dtype=torch_dtype)
  File "C:\Users\whyask37\Documents\comfy\ComfyUI\custom_nodes\ComfyUI-nunchaku\model_configs\zimage.py", line 71, in get_model
    patch_model(
    ~~~~~~~~~~~^
        out.diffusion_model, skip_refiners=self.skip_refiners, rank=self.rank, precision=self.precision, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\whyask37\Documents\comfy\ComfyUI\custom_nodes\ComfyUI-nunchaku\models\zimage.py", line 320, in patch_model
    _patch_transformer_block(diffusion_model.layers)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\whyask37\Documents\comfy\ComfyUI\custom_nodes\ComfyUI-nunchaku\models\zimage.py", line 317, in _patch_transformer_block
    block.attention = ComfyNunchakuZImageAttention(block.attention, **kwargs)
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\whyask37\Documents\comfy\ComfyUI\custom_nodes\ComfyUI-nunchaku\models\zimage.py", line 133, in __init__
    self.qkv = SVDQW4A4Linear.from_linear(orig_attn.qkv, **kwargs)
               ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\whyask37\miniconda3\envs\comfyui\Lib\site-packages\nunchaku\models\linear.py", line 152, in from_linear
    torch_dtype = kwargs.pop("torch_dtype", linear.weight.dtype)
                                            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'dtype'
```

**Comment by coddz** [comment]
me too.

win11
comfyui portable(upgrade to the latest ComfyUI Version: v0.15.1-34-gf719a9d9 | Released on '2026-03-03') 
comfyui_nunchaku 1.2.1+nunchaku whl 1.2.1 

maybe this issue is caused by the changing of comfyui core, 

got prompt
Using xformers attention in VAE
Using xformers attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
Requested to load ZImageTEModel_
Model ZImageTEModel_ prepared for dynamic VRAM loading. 7671MB Staged. 0 patches attached. Force pre-loaded 145 weights: 383 KB.
unet_dtype: torch.bfloat16, manual_cast_dtype: None, svdq_linear_dtype: torch.bfloat16
model weight dtype torch.bfloat16, manual cast: None
model_type FLOW
!!! Exception during processing !!! 'NoneType' object has no attribute 'dtype'
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 524, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 333, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 307, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 295, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nunchaku\nodes\models\zimage.py", line 215, in load_model
    model = _load(sd, metadata=metadata)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nunchaku\nodes\models\zimage.py", line 148, in _load
    model = model_config.get_model(patched_sd, "", torch_dtype=torch_dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nunchaku\model_configs\zimage.py", line 71, in get_model
    patch_model(
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nunchaku\models\zimage.py", line 320, in patch_model
    _patch_transformer_block(diffusion_model.layers)
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nunchaku\models\zimage.py", line 317, in _patch_transformer_block
    block.attention = ComfyNunchakuZImageAttention(block.attention, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nunchaku\models\zimage.py", line 133, in __init__
    self.qkv = SVDQW4A4Linear.from_linear(orig_attn.qkv, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\nunchaku\models\linear.py", line 152, in from_linear
    torch_dtype = kwargs.pop("torch_dtype", linear.weight.dtype)
                                            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'dtype'

Prompt executed in 4.69 seconds

**Comment by fabianakker** [comment]
it also happens with the ComfyUI-Easy-Install portable build on 0.15.1 where DynamicVRAM is enabled by default (not just --fast), 

Launching ComfyUI with --disable-dynamic-vram is the workaround.

**Comment by liulin900** [comment]
It seems to conflict with SageAttention

**Comment by kukukutaragi-alt** [comment]
anyone fixed the issue?

**Comment by devsynck** [comment]
Suggestion of @fabianakker worked for me. Thanks!

**Comment by boy530064320** [comment]
特别感谢Michelle-HCJ大佬的邮件指点我，顾特此分享出来，给同样遇到问题的大家提供方便

![Image](https://github.com/user-attachments/assets/3b67e3bd-fb04-439a-b693-a1bd251d1198)

<img width="896" height="743" alt="Image" src="https://github.com/user-attachments/assets/07679f9f-990b-4cf4-8e16-3d9c717dcc38" />

![Image](https://github.com/user-attachments/assets/00084ec5-ae68-4659-94b7-e3f8e8ae83a5)

**Comment by Orenji-Tangerine** [comment]
Thx for the fix...

**Comment by CrystianS** [comment]
> --disable-dynamic-vram

Thanks. Lost almost 2 days trying to figure what was happening, searching workflows in youtube, asking AI. I was about to give up and came here.

**Comment by GZDDMZ** [comment]
> it also happens with the ComfyUI-Easy-Install portable build on 0.15.1 where DynamicVRAM is enabled by default (not just --fast),在 0.15.1 版本的 ComfyUI-Easy-Install 便携版中也会出现这种情况，该版本默认启用了 DynamicVRAM（而不仅仅是 --fast 模式）。
> 
> Launching ComfyUI with --disable-dynamic-vram is the workaround.使用 --disable-dynamic-vram 参数启动 ComfyUI 是一种解决方法。

A code-level workaround that fixed this for me:

The crash is caused by code paths that assume `nn.Linear.weight` is always present. With `--fast` / DynamicVRAM, Comfy can leave `linear.weight` as `None` and keep the dtype on Comfy-specific attrs instead, so direct reads like `linear.weight.dtype` or `linear.weight.device` explode.

In my setup the installed `nunchaku` package already had the fallback in `SVDQW4A4Linear.from_linear(...)`, but `ComfyUI-nunchaku/models/zimage.py::fuse_to_svdquant_linear(...)` still needed the same treatment.

I changed it to resolve dtype/device like this instead of reading `comfy_linear1.weight.dtype` directly:

```python
weight1 = getattr(comfy_linear1, "weight", None)
bias1 = getattr(comfy_linear1, "bias", None)

torch_dtype = kwargs.pop("torch_dtype", None)
if torch_dtype is None:
    if weight1 is not None:
        torch_dtype = weight1.dtype
    else:
        torch_dtype = getattr(comfy_linear1, "weight_comfy_model_dtype", None)
if torch_dtype is None:
    if bias1 is not None:
        torch_dtype = bias1.dtype
    else:
        torch_dtype = getattr(comfy_linear1, "bias_comfy_model_dtype", None)
if torch_dtype is None:
    torch_dtype = torch.bfloat16

device = kwargs.pop("device", None)
if device is None:
    if weight1 is not None:
        device = weight1.device
    elif bias1 is not None:
        device = bias1.device
```
If your site-packages/nunchaku/models/linear.py still contains the older kwargs.pop("torch_dtype", linear.weight.dtype) line from the traceback, update/patch that file too with the same fallback logic.

After that, Z-Image-Turbo started generating again for me with comfy launch -- --fast, without needing --disable-dynamic-vram.

**Comment by stuartluscombe** [comment]
The fix from @GZDDMZ does work. But only if you're running without SageAttention (as mentioned by @liulin900).

For reference of anyone coming across this before it is officially patched, the full function should read like this

```python
def fuse_to_svdquant_linear(comfy_linear1: nn.Linear, comfy_linear2: nn.Linear, **kwargs) -> SVDQW4A4Linear:
    """
    Fuse two linear modules into one SVDQW4A4Linear.

    The two linear modules MUST have equal `in_features`.

    Parameters
    ----------
    comfy_linear1 : nn.Linear
        linear module 1
    comfy_linear2 : nn.Linear
        linear module 2

    Returns
    -------
    SVDQW4A4Linear:
        The fused module.
    """
    assert comfy_linear1.in_features == comfy_linear2.in_features
    assert comfy_linear1.bias is None and comfy_linear2.bias is None

    weight1 = getattr(comfy_linear1, "weight", None)
    bias1 = getattr(comfy_linear1, "bias", None)

    torch_dtype = kwargs.pop("torch_dtype", None)
    if torch_dtype is None:
        if weight1 is not None:
            torch_dtype = weight1.dtype
        else:
            torch_dtype = getattr(comfy_linear1, "weight_comfy_model_dtype", None)
    if torch_dtype is None:
        if bias1 is not None:
            torch_dtype = bias1.dtype
        else:
            torch_dtype = getattr(comfy_linear1, "bias_comfy_model_dtype", None)
    if torch_dtype is None:
        torch_dtype = torch.bfloat16

    device = kwargs.pop("device", None)
    if device is None:
        if weight1 is not None:
            device = weight1.device
        elif bias1 is not None:
            device = bias1.device

    svdq_linear = SVDQW4A4Linear(
        comfy_linear1.in_features,
        comfy_linear1.out_features + comfy_linear2.out_features,
        bias=False,
        torch_dtype=torch_dtype,
        device=device,
        **kwargs,
    )
    add_comfy_cast_weights_attr(svdq_linear, comfy_linear1)
    return svdq_linear
```

**Comment by sjcta** [comment]
我修改 numchaku_nodes/models/zimage.py 以下函数后可以正常跑起来了，带不带--fast 都可以 ：


    assert comfy_linear1.in_features == comfy_linear2.in_features
    assert comfy_linear1.bias is None and comfy_linear2.bias is None
    # Handle low VRAM mode where weight might be None
    if comfy_linear1.weight is not None:
        torch_dtype = kwargs.pop("torch_dtype", comfy_linear1.weight.dtype)
        device = comfy_linear1.weight.device
    elif comfy_linear2.weight is not None:
        torch_dtype = kwargs.pop("torch_dtype", comfy_linear2.weight.dtype)
        device = comfy_linear2.weight.device
    else:
        # Fallback: use torch_dtype from kwargs or default to bfloat16
        torch_dtype = kwargs.pop("torch_dtype", torch.bfloat16)
        device = None
    svdq_linear = SVDQW4A4Linear(
        comfy_linear1.in_features,
        comfy_linear1.out_features + comfy_linear2.out_features,
        bias=False,
        torch_dtype=torch_dtype,
        device=device,
        **kwargs,
    )

**Comment by psylo1138-dotcom** [comment]
Still have the problem... I don't know code but tried the modif but it didn't work... I use the https://github.com/Tavris1/ComfyUI-Easy-Install and had to add the --disable-dynamic-vram command in the .bat file but would like a solution to keep dynamic vram enabled.

**Comment by deepdeacon** [comment]
I can confirm this issue also occurs on RTX 50-series (Blackwell) with FP4 models, even without --fast, using the ComfyUI Easy-Install portable setup.

In my case:
GPU: GeForce RTX 5080  
Model: svdq-fp4_r128-z-image-turbo.safetensors  
DynamicVRAM appears to trigger the same behavior as --fast.

This is not limited to ComfyUI-Easy-Install\python_embeded\Lib\site-packages\nunchaku\models\linear.py. The same crash pattern also occurs in ComfyUI-Easy-Install\ComfyUI\custom_nodes\ComfyUI-nunchaku\models\zimage.py. The failure is caused by accessing .weight.dtype or .weight.device when linear.weight is None.

In linear.py (lines 151–160), the original code:
```
in_features = kwargs.pop("in_features", linear.in_features)
torch_dtype = kwargs.pop("torch_dtype", linear.weight.dtype)
return cls(
    in_features=in_features,
    out_features=linear.out_features,
    bias=linear.bias is not None,
    torch_dtype=torch_dtype,
    device=linear.weight.device,
    **kwargs,
)
```
I changed to:
```
in_features = kwargs.pop("in_features", linear.in_features)

torch_dtype = kwargs.pop("torch_dtype", None)
if torch_dtype is None and linear.weight is not None:
    torch_dtype = linear.weight.dtype

device = kwargs.pop("device", None)
if device is None and linear.weight is not None:
    device = linear.weight.device

return cls(
    in_features=in_features,
    out_features=linear.out_features,
    bias=linear.bias is not None,
    torch_dtype=torch_dtype,
    device=device,
    **kwargs,
)
```
In zimage.py (lines 60–72), the original code:
```
torch_dtype = kwargs.pop("torch_dtype", comfy_linear1.weight.dtype)

svdq_linear = SVDQW4A4Linear(
    comfy_linear1.in_features,
    comfy_linear1.out_features + comfy_linear2.out_features,
    bias=False,
    torch_dtype=torch_dtype,
    device=comfy_linear1.weight.device,
    **kwargs,
)
```
I changed to:
```
torch_dtype = kwargs.pop("torch_dtype", None)
if torch_dtype is None and comfy_linear1.weight is not None:
    torch_dtype = comfy_linear1.weight.dtype

device = kwargs.pop("device", None)
if device is None and comfy_linear1.weight is not None:
    device = comfy_linear1.weight.device

svdq_linear = SVDQW4A4Linear(
    comfy_linear1.in_features,
    comfy_linear1.out_features + comfy_linear2.out_features,
    bias=False,
    torch_dtype=torch_dtype,
    device=device,
    **kwargs,
)
```
After applying this pattern in both files, the FP4 model loads correctly, and the full workflow runs successfully using the standard Start ComfyUI.bat with no need for --disable-dynamic-vram

This appears to be a broader assumption issue across multiple code paths, not just a single function. It may be worth applying a safe fallback pattern anywhere `*.weight.dtype` or `*.weight.device` is accessed.

Hopefully this helps anyone else using the ComfyUI-Easy-Install portable version.

**Comment by byron-dm** [comment]
Strangely, none of the above changes did the trick for me.

Using the code from #817 finally worked

**Comment by OCOMATA** [comment]
Doesn't work for me either...

**Comment by FNGarvin** [comment]
@OCOMATA #817 along with the corresponding https://github.com/nunchaku-ai/nunchaku/pull/929 worked for me just a few days ago.

**Comment by courtjestr** [comment]
#817 with #929 works for me as well. Note that CFG had to be 1. Anything else leads to a crash.
